namespace Volo.Abp.Identity.ExternalLogin.EntityFrameworkCore;
public abstract class VoloAbpIdentityExternalLoginEntityFrameworkCoreTestBase : VoloAbpIdentityExternalLoginTestBase<VoloAbpIdentityExternalLoginEntityFrameworkCoreTestModule>
{
}
