namespace KTTW.Abp.Identity.ExternalLogin.Abstract;

public abstract class KTTWAbpIdentityExternalLoginAbstractTestBase : KTTWAbpIdentityExternalLoginTestBase<KTTWAbpIdentityExternalLoginAbstractTestModule>
{
}
