namespace Volo.Abp.Identity.ExternalLogin.Abstract;

public abstract class VoloAbpIdentityExternalLoginAbstractTestBase : VoloAbpIdentityExternalLoginTestBase<VoloAbpIdentityExternalLoginAbstractTestModule>
{
}
