namespace KTTW.Abp.Identity.ExternalLogin.EntityFrameworkCore;
public abstract class KTTWAbpIdentityExternalLoginEntityFrameworkCoreTestBase : KTTWAbpIdentityExternalLoginTestBase<KTTWAbpIdentityExternalLoginEntityFrameworkCoreTestModule>
{
}
